model_object: FIBO
model_config: fibo
model_cli_generate_command: mflux-generate-fibo
hf_model_name: briaai/FIBO
quants:
  - q3
  - q4
  - q5
  - q6
  - q8
  - bf16
collection:
  name: Fibo
  description: MFlux quantized builds of Fibo
  version: 1.0.0